### ISSUE TITLE
「色設定」で薄い色を選択した時にテキストが読めない

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#108]
<img width="270" alt="スクリーンショット 2022-01-16 11 53 58" src="https://user-images.githubusercontent.com/31400297/149645529-b5870faf-54e6-4795-9520-9ec3b3097ef1.png">

以下のコードで対応
```css
    .components-color-palette__custom-color[style*="--color_pale"],
    .components-color-palette__custom-color[style*="--color_main_thin"],
    .components-color-palette__custom-color[style*="--color_gray"] {
        color: #000 !important;
    }
```
