### ISSUE TITLE
説明リスト(DL)ブロック: スタイルが正しく当たっていない

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#12]
説明リスト(DL)ブロックのedit側で、API v2化に伴う`useInnerBlocksProps` でおそらくDOM構造が変わった事で、`src/scss/editor/block/_swell-dl.scss`の以下のスタイルが当たらなくなっています。

```scss
.is-style-vtabel {

    > .swell-block-dl__dt {
        margin-top: 0;
        padding: .5em 1em;
        color: #fff;
        background-color: var(--color_main);
    }
}
```

![dl](https://user-images.githubusercontent.com/54422211/127496633-50bd7016-2005-4475-b4c8-93c840788b27.png)
