### ISSUE TITLE
チェックボックスのチェックマークの色が黒くなっている

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#241]
以下のCSSで、`fill: #fff;` が上書きされているため

```css
svg:not([fill]) {
    fill: currentColor;
}
```

![svg](https://user-images.githubusercontent.com/54422211/167366625-6c7e200b-497a-478d-b7ca-fc8aef80729c.png)
