### ISSUE TITLE
カラーパレットにカラーラベル・カラー値が表示される

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#253]
以下PRにより、Gutenberg 12.9から、カラーパレットにラベル・値が表示されるようになった。
※値からは、「`#`」が取り除かれる
https://github.com/WordPress/gutenberg/pull/39386

JS側では介入する余地がないため、CSSで対応するしかないと思われます。

## 例

- カラーラベルは常に非表示
- カラー値は、CSS変数の場合は非表示にする

### コード例

`src/scss/editor/gutenberg-ui/controls/_core-colorPanel.scss`

```scss
// カラーコードに変数が使われている場合は値を非表示にする
.components-color-palette__custom-color[style*="--color_main"],
.components-color-palette__custom-color[style*="--color_main"],
.components-color-palette__custom-color[style*="--color_gray"],
.components-color-palette__custom-color[style*="--color_deep"],
.components-color-palette__custom-color[style*="--color_pale"] {

    .components-color-palette__custom-color-value {
        visibility: hidden;
    }
}

// カラーパレットの透明パターン非表示
.components-circular-option-picker__option-wrapper::before {
    background: none;
}
```

### Before 

https://user-images.githubusercontent.com/54422211/169237790-5cd75288-cb3f-45d7-ad0f-18ec433967d7.mp4

### After

https://user-images.githubusercontent.com/54422211/169237776-8e6b0993-e0a9-4f46-afd1-e45974858ed5.mp4
