### ISSUE TITLE
区切りブロックで、エディター側で背景色の設定が反映されない。

### ISSUE THREAD

**Issue by ddryo** [loos/SWELL#257]
区切りブロックで、エディター側で背景色の設定が反映されない。
（「ドット」スタイルのみは正常に反映される）

![separator](https://user-images.githubusercontent.com/54422211/167600279-01b0b458-0779-4314-8c76-45330f859832.png)

_Originally posted by @t-hamano in https://github.com/loos/SWELL/issues/235#issuecomment-1122168360_

**Comment by ddryo** [comment]
@t-hamano エディター上で、has-background系のクラスが付与されなくなってhas-text-color しかなくなっているのですが、コアの不具合な気がします...。

**Comment by ddryo** [comment]
has-backgroundがなくなっていることで、TT2でもグラデーションにした時にエディター側で反映されなくなっています。

<img width="1057" alt="スクリーンショット 2022-05-20 11 14 02" src="https://user-images.githubusercontent.com/31400297/169435377-04b563de-1513-4de1-8ad2-577d5ab73fd5.png">

<img width="729" alt="スクリーンショット 2022-05-20 11 13 37" src="https://user-images.githubusercontent.com/31400297/169435382-411076ee-2b4c-4921-be50-03a9ef54d36f.png">

**Comment by t-hamano** [comment]
取り急ぎ、5.9 / 6.0 両方のエディターでの表示を調整したスタイルです。
ただし、ブロックをクリックする領域が1pxだけなので、ボーダーは疑似要素で表現、paddingでブロックに余白を持たせた方が良いかもしれません

`src/scss/modules/blocks/separator.scss`

```scss
.wp-block-separator {
    // テキスト色用クラス（has-xxx-color）で背景色を埋める
    background-color: currentColor;
    // deparacatedなブロックにはopacity0.4がつくので上書きする
    // see:https://github.com/WordPress/gutenberg/blob/c9e1159f00ebcb3fd611082a57666d88af71fa41/packages/block-library/src/separator/deprecated.scss
    opacity: 1 !important;

    &:not(.is-style-dots) {
        // 6.0でbox-sizingが当たらなくなったため
        box-sizing: border-box;
        // コアスタイルのheight:2pxを上書きする
        height: 1px !important;
        // コアスタイルで、上下に0.1pxのpaddingが付くのを上書きする
        // see:https://github.com/WordPress/gutenberg/blob/c840e90376da5de3e73af9499571e66fc8f25ff4/packages/block-library/src/separator/editor.scss#L3-L4
        padding: 0;
    }

    &:not(.is-style-wide):not(.is-style-dots) {
        max-width: 100px;
        margin-right: auto;
        margin-left: auto;
    }
}
```

**Comment by t-hamano** [comment]
issue上げました。
https://github.com/WordPress/gutenberg/issues/41194

**Comment by ddryo** [comment]
> // deparacatedなブロックにはopacity0.4がつくので上書きする

これってどういう時に付きますかね？

**Comment by t-hamano** [comment]
> // deparacatedなブロックにはopacity0.4がつくので上書きする
> これってどういう時に付きますかね？

再現手順を記載しますと、

- WP5.9で区切りブロックを挿入する
- WP6.0のエディターにコピペする
- ブロックに .`has-css-opaciy` というクラスがつく
- 以下CSSにより、`opacity:0.4` が適用される

```scss
.wp-block-separator.has-css-opacity {
    opacity: .4;
}
```

となります。

つまり、5.9 → 6.0 アップデートでブロックがv1 → v2にmigrateされた時に、v1のデフォルトスタイルである `opacity:0.4` を保持するために、migrate時に `has-css-opacity` というクラスをつけてそこにスタイルを当てている、という事かなと思います。
