### ISSUE TITLE
フォントサイズバリエーションが上書きされてしまっている

### ISSUE THREAD

**Issue by t-hamano** [loos/SWELL#57]
全てのブロックでフォントサイズバリエーションが上書きされてしまっている。
フォントサイズ用クラス（`.has-{slug}-font-size`）がコア側でグローバル変数を使ったimportantな値を出力するようになったため。

![148532949-2884b0e5-5d47-48ec-88de-4dceaf27dc9e](https://user-images.githubusercontent.com/54422211/148635246-3991f8c4-0798-455b-913a-fecbf1b2835f.png)

**Comment by t-hamano** [comment]
SWELL側のフォントサイズバリエーション（`editor-font-sizes`）は `xs` / `small` / `medium` / `large` / `large` / `huge` だが、`xs` 以外のフォントサイズが、以下のスラッグが重複しているコアスタイルで上書きされてしまう。

```css
.editor-styles-wrapper .has-small-font-size {
    font-size: var(--wp--preset--font-size--small) !important;
}
.editor-styles-wrapper .has-medium-font-size {
    font-size: var(--wp--preset--font-size--medium) !important;
}
.editor-styles-wrapper .has-large-font-size {
    font-size: var(--wp--preset--font-size--large) !important;
}
.editor-styles-wrapper .has-huge-font-size {
    font-size: var(--wp--preset--font-size--huge) !important;
}
```

`theme-json` を設置しないで、上記CSS変数を上書きする方法を調べてみる。
